import { StateCodes } from '@nfets/core';

export default {
  [StateCodes.AC]: 'SVCAN',
  [StateCodes.AL]: 'SVCAN',
  [StateCodes.AM]: 'SVCRS',
  [StateCodes.AP]: 'SVCAN',
  [StateCodes.BA]: 'SVCRS',
  [StateCodes.CE]: 'SVCAN',
  [StateCodes.DF]: 'SVCAN',
  [StateCodes.ES]: 'SVCAN',
  [StateCodes.GO]: 'SVCRS',
  [StateCodes.MA]: 'SVCRS',
  [StateCodes.MG]: 'SVCAN',
  [StateCodes.MS]: 'SVCRS',
  [StateCodes.MT]: 'SVCRS',
  [StateCodes.PA]: 'SVCAN',
  [StateCodes.PB]: 'SVCAN',
  [StateCodes.PE]: 'SVCRS',
  [StateCodes.PI]: 'SVCAN',
  [StateCodes.PR]: 'SVCRS',
  [StateCodes.RJ]: 'SVCAN',
  [StateCodes.RN]: 'SVCAN',
  [StateCodes.RO]: 'SVCAN',
  [StateCodes.RR]: 'SVCAN',
  [StateCodes.RS]: 'SVCAN',
  [StateCodes.SC]: 'SVCAN',
  [StateCodes.SE]: 'SVCAN',
  [StateCodes.SP]: 'SVCAN',
  [StateCodes.TO]: 'SVCAN',
} as const;
