import { Environment, UF } from '@nfets/core';

export default {
  [Environment.Homolog]: {
    [UF.AC]: 'www.sefaznet.ac.gov.br/nfce/consulta',
    [UF.AL]: 'www.sefaz.al.gov.br/nfce/consulta',
    [UF.AP]: 'www.sefaz.ap.gov.br/nfce/consulta',
    [UF.AM]: 'www.sefaz.am.gov.br/nfce/consulta',
    [UF.BA]: 'http://hinternet.sefaz.ba.gov.br/nfce/consulta',
    [UF.CE]: 'www.sefaz.ce.gov.br/nfce/consulta',
    [UF.DF]: 'www.fazenda.df.gov.br/nfce/consulta',
    [UF.ES]: 'www.sefaz.es.gov.br/nfce/consulta',
    [UF.GO]: 'www.nfce.go.gov.br/post/ver/214413/consulta-nfc-e-homologacao',
    [UF.MA]: 'www.sefaz.ma.gov.br/nfce/consulta',
    [UF.MG]: 'https://hportalsped.fazenda.mg.gov.br/portalnfce',
    [UF.MS]: 'http://www.dfe.ms.gov.br/nfce/consulta',
    [UF.MT]: 'http://homologacao.sefaz.mt.gov.br/nfce/consultanfce',
    [UF.PA]: 'www.sefa.pa.gov.br/nfce/consulta',
    [UF.PB]: 'www.sefaz.pb.gov.br/nfcehom',
    [UF.PE]: 'nfce.sefaz.pe.gov.br/nfce/consulta',
    [UF.PR]: 'http://www.fazenda.pr.gov.br/nfce/consulta',
    [UF.PI]: 'www.sefaz.pi.gov.br/nfce/consulta',
    [UF.RJ]: 'www.fazenda.rj.gov.br/nfce/consulta',
    [UF.RN]: 'www.set.rn.gov.br/nfce/consulta',
    [UF.RO]: 'www.sefin.ro.gov.br/nfce/consulta',
    [UF.RR]: 'www.sefaz.rr.gov.br/nfce/consulta',
    [UF.RS]: 'www.sefaz.rs.gov.br/nfce/consulta',
    [UF.SE]: 'http://www.hom.nfe.se.gov.br/nfce/consulta',
    [UF.SC]: 'https://hom.sat.sef.sc.gov.br/nfce/consulta',
    [UF.SP]:
      'https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica',
    [UF.TO]: 'http://homologacao.sefaz.to.gov.br/nfce/consulta.jsf',
  },
  [Environment.Production]: {
    [UF.AC]: 'www.sefaznet.ac.gov.br/nfce/consulta',
    [UF.AL]: 'www.sefaz.al.gov.br/nfce/consulta',
    [UF.AP]: 'www.sefaz.ap.gov.br/nfce/consulta',
    [UF.AM]: 'www.sefaz.am.gov.br/nfce/consulta',
    [UF.BA]: 'http://www.sefaz.ba.gov.br/nfce/consulta',
    [UF.CE]: 'www.sefaz.ce.gov.br/nfce/consulta',
    [UF.DF]: 'www.fazenda.df.gov.br/nfce/consulta',
    [UF.ES]: 'www.sefaz.es.gov.br/nfce/consulta',
    [UF.GO]: 'www.sefaz.go.gov.br/nfce/consulta',
    [UF.MA]: 'www.sefaz.ma.gov.br/nfce/consulta',
    [UF.MG]: 'https://portalsped.fazenda.mg.gov.br/portalnfce',
    [UF.MS]: 'http://www.dfe.ms.gov.br/nfce/consulta',
    [UF.MT]: 'http://www.sefaz.mt.gov.br/nfce/consultanfce',
    [UF.PA]: 'www.sefa.pa.gov.br/nfce/consulta',
    [UF.PE]: 'nfce.sefaz.pe.gov.br/nfce/consulta',
    [UF.PR]: 'http://www.fazenda.pr.gov.br/nfce/consulta',
    [UF.PI]: 'www.sefaz.pi.gov.br/nfce/consulta',
    [UF.RJ]: 'www.fazenda.rj.gov.br/nfce/consulta',
    [UF.RN]: 'www.set.rn.gov.br/nfce/consulta',
    [UF.RO]: 'www.sefin.ro.gov.br/nfce/consulta',
    [UF.RR]: 'www.sefaz.rr.gov.br/nfce/consulta',
    [UF.RS]: 'www.sefaz.rs.gov.br/nfce/consulta',
    [UF.SC]: 'https://sat.sef.sc.gov.br/nfce/consulta',
    [UF.SE]: 'http://www.nfce.se.gov.br/nfce/consulta',
    [UF.SP]: 'https://www.nfce.fazenda.sp.gov.br/NFCeConsultaPublica',
    [UF.TO]: 'www.sefaz.to.gov.br/nfce/consulta',
    [UF.PB]: 'www.sefaz.pb.gov.br/nfce/consulta',
  },
} as const;
