import { Environment, StateCodes } from '@nfets/core';

export default {
  [Environment.Homolog]: {
    [StateCodes.AC]: 'www.sefaznet.ac.gov.br/nfce/consulta',
    [StateCodes.AL]: 'www.sefaz.al.gov.br/nfce/consulta',
    [StateCodes.AP]: 'www.sefaz.ap.gov.br/nfce/consulta',
    [StateCodes.AM]: 'www.sefaz.am.gov.br/nfce/consulta',
    [StateCodes.BA]: 'http://hinternet.sefaz.ba.gov.br/nfce/consulta',
    [StateCodes.CE]: 'www.sefaz.ce.gov.br/nfce/consulta',
    [StateCodes.DF]: 'www.fazenda.df.gov.br/nfce/consulta',
    [StateCodes.ES]: 'www.sefaz.es.gov.br/nfce/consulta',
    [StateCodes.GO]:
      'www.nfce.go.gov.br/post/ver/214413/consulta-nfc-e-homologacao',
    [StateCodes.MA]: 'www.sefaz.ma.gov.br/nfce/consulta',
    [StateCodes.MG]: 'https://hportalsped.fazenda.mg.gov.br/portalnfce',
    [StateCodes.MS]: 'http://www.dfe.ms.gov.br/nfce/consulta',
    [StateCodes.MT]: 'http://homologacao.sefaz.mt.gov.br/nfce/consultanfce',
    [StateCodes.PA]: 'www.sefa.pa.gov.br/nfce/consulta',
    [StateCodes.PB]: 'www.sefaz.pb.gov.br/nfcehom',
    [StateCodes.PE]: 'nfce.sefaz.pe.gov.br/nfce/consulta',
    [StateCodes.PR]: 'http://www.fazenda.pr.gov.br/nfce/consulta',
    [StateCodes.PI]: 'www.sefaz.pi.gov.br/nfce/consulta',
    [StateCodes.RJ]: 'www.fazenda.rj.gov.br/nfce/consulta',
    [StateCodes.RN]: 'www.set.rn.gov.br/nfce/consulta',
    [StateCodes.RO]: 'www.sefin.ro.gov.br/nfce/consulta',
    [StateCodes.RR]: 'www.sefaz.rr.gov.br/nfce/consulta',
    [StateCodes.RS]: 'www.sefaz.rs.gov.br/nfce/consulta',
    [StateCodes.SE]: 'http://www.hom.nfe.se.gov.br/nfce/consulta',
    [StateCodes.SC]: 'https://hom.sat.sef.sc.gov.br/nfce/consulta',
    [StateCodes.SP]:
      'https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica',
    [StateCodes.TO]: 'http://homologacao.sefaz.to.gov.br/nfce/consulta.jsf',
  },
  [Environment.Production]: {
    [StateCodes.AC]: 'www.sefaznet.ac.gov.br/nfce/consulta',
    [StateCodes.AL]: 'www.sefaz.al.gov.br/nfce/consulta',
    [StateCodes.AP]: 'www.sefaz.ap.gov.br/nfce/consulta',
    [StateCodes.AM]: 'www.sefaz.am.gov.br/nfce/consulta',
    [StateCodes.BA]: 'http://www.sefaz.ba.gov.br/nfce/consulta',
    [StateCodes.CE]: 'www.sefaz.ce.gov.br/nfce/consulta',
    [StateCodes.DF]: 'www.fazenda.df.gov.br/nfce/consulta',
    [StateCodes.ES]: 'www.sefaz.es.gov.br/nfce/consulta',
    [StateCodes.GO]: 'www.sefaz.go.gov.br/nfce/consulta',
    [StateCodes.MA]: 'www.sefaz.ma.gov.br/nfce/consulta',
    [StateCodes.MG]: 'https://portalsped.fazenda.mg.gov.br/portalnfce',
    [StateCodes.MS]: 'http://www.dfe.ms.gov.br/nfce/consulta',
    [StateCodes.MT]: 'http://www.sefaz.mt.gov.br/nfce/consultanfce',
    [StateCodes.PA]: 'www.sefa.pa.gov.br/nfce/consulta',
    [StateCodes.PE]: 'nfce.sefaz.pe.gov.br/nfce/consulta',
    [StateCodes.PR]: 'http://www.fazenda.pr.gov.br/nfce/consulta',
    [StateCodes.PI]: 'www.sefaz.pi.gov.br/nfce/consulta',
    [StateCodes.RJ]: 'www.fazenda.rj.gov.br/nfce/consulta',
    [StateCodes.RN]: 'www.set.rn.gov.br/nfce/consulta',
    [StateCodes.RO]: 'www.sefin.ro.gov.br/nfce/consulta',
    [StateCodes.RR]: 'www.sefaz.rr.gov.br/nfce/consulta',
    [StateCodes.RS]: 'www.sefaz.rs.gov.br/nfce/consulta',
    [StateCodes.SC]: 'https://sat.sef.sc.gov.br/nfce/consulta',
    [StateCodes.SE]: 'http://www.nfce.se.gov.br/nfce/consulta',
    [StateCodes.SP]: 'https://www.nfce.fazenda.sp.gov.br/NFCeConsultaPublica',
    [StateCodes.TO]: 'www.sefaz.to.gov.br/nfce/consulta',
    [StateCodes.PB]: 'www.sefaz.pb.gov.br/nfce/consulta',
  },
} as const;
