name: Setup Environment
description: A reusable composite action to setup the environment.
inputs:
  os:
    description: The operating system to setup.
    required: true
  node-version:
    description: The Node.js version to setup.
    required: true
  architecture:
    description: The architecture to setup the node.js.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        architecture: ${{ inputs.architecture }}
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Install Linux packages
      if: contains(inputs.os, 'ubuntu')
      run: sudo apt update && sudo apt install -y libxml2-dev
      shell: bash

    - name: Install macOS packages
      if: contains(inputs.os, 'macos')
      run: brew install libxml2 pkg-config
      shell: bash

    - name: Install Windows packages (x64 and x86)
      id: msys2
      if: contains(inputs.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: UCRT64
        install: mingw-w64-ucrt-x86_64-libxml2 mingw-w64-ucrt-i686-libxml2 libxml2

    - run: Get-ChildItem -Path "C:\msys64\ucrt64" -Recurse -Depth 4
      continue-on-error: true
      if: contains(inputs.os, 'windows')
      shell: pwsh

    # - name: Install Windows packages
    #   if: contains(inputs.os, 'windows')
    #   shell: pwsh
    #   run: |
    #     if ("${{ inputs.architecture }}" -eq "x86") {
    #       $TRIPLET = "x86-windows"
    #     } else {
    #       Write-Error "Unsupported Windows architecture: ${{ inputs.architecture }}"
    #       exit 1
    #     }

    #     Write-Host "Installing libxml2:$TRIPLET..."
    #     & C:\vcpkg\vcpkg.exe install libxml2:$TRIPLET
    #     if ($LASTEXITCODE -ne 0) {
    #       Write-Error "Failed to install libxml2"
    #       exit 1
    #     }

    #     $VCPKG_ROOT = "C:\vcpkg"
    #     $LIBXML2_DIR = "$VCPKG_ROOT\installed\$TRIPLET\include"
    #     $LIBXML2_LIB = "$VCPKG_ROOT\installed\$TRIPLET\lib\xml2.lib"

    #     # Check what's actually in the include directory
    #     Write-Host "Checking contents of ${LIBXML2_DIR}:"
    #     if (Test-Path $LIBXML2_DIR) {
    #       Get-ChildItem $LIBXML2_DIR -ErrorAction SilentlyContinue | Select-Object -First 20 | ForEach-Object { Write-Host "  $($_.Name)" }
    #     } else {
    #       Write-Host "  Directory does not exist"
    #     }

    #     # Find parser.h - it should be in libxml subdirectory
    #     # The include path should be set so that #include <libxml/parser.h> works
    #     $PARSER_H_PATH = "$LIBXML2_DIR\libxml\parser.h"
    #     if (-not (Test-Path $PARSER_H_PATH)) {
    #       # Search for parser.h recursively
    #       $FOUND_PARSER = Get-ChildItem -Path $LIBXML2_DIR -Filter "parser.h" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
    #       if ($FOUND_PARSER) {
    #         Write-Host "Found parser.h at: $($FOUND_PARSER.FullName)"
    #         # parser.h should be in a libxml subdirectory
    #         # LIBXML2_DIR should point to the directory that contains the libxml subdirectory
    #         if ($FOUND_PARSER.Directory.Name -eq "libxml") {
    #           # parser.h is in libxml subdirectory, so parent is the include dir
    #           $LIBXML2_DIR = $FOUND_PARSER.Directory.Parent.FullName
    #           Write-Host "Updated LIBXML2_DIR to: $LIBXML2_DIR"
    #         } else {
    #           Write-Error "parser.h found but not in expected libxml subdirectory. Found at: $($FOUND_PARSER.FullName)"
    #           exit 1
    #         }
    #       } else {
    #         Write-Error "libxml2 headers not found. Searched for parser.h in $LIBXML2_DIR"
    #         Write-Host "Contents of ${LIBXML2_DIR}:"
    #         Get-ChildItem $LIBXML2_DIR -ErrorAction SilentlyContinue | Select-Object -First 20
    #         exit 1
    #       }
    #     } else {
    #       Write-Host "Found parser.h at expected location: $PARSER_H_PATH"
    #     }

    #     # Verify library exists
    #     if (-not (Test-Path $LIBXML2_LIB)) {
    #       # Try to find xml2.lib
    #       $FOUND_LIB = Get-ChildItem -Path "$VCPKG_ROOT\installed\$TRIPLET\lib" -Filter "xml2.lib" -ErrorAction SilentlyContinue | Select-Object -First 1
    #       if ($FOUND_LIB) {
    #         $LIBXML2_LIB = $FOUND_LIB.FullName
    #         Write-Host "Found xml2.lib at: $LIBXML2_LIB"
    #       } else {
    #         Write-Error "libxml2 library not found at $LIBXML2_LIB"
    #         Write-Host "Contents of ${VCPKG_ROOT}\installed\${TRIPLET}\lib:"
    #         Get-ChildItem "$VCPKG_ROOT\installed\$TRIPLET\lib" -ErrorAction SilentlyContinue | Select-Object -First 20
    #         exit 1
    #       }
    #     }

    #     Write-Host "Setting LIBXML2_DIR=$LIBXML2_DIR"
    #     Write-Host "Setting LIBXML2_LIB=$LIBXML2_LIB"

    #     $LIBXML2_DIR_NORMALIZED = $LIBXML2_DIR -replace '\\', '/'
    #     $LIBXML2_LIB_NORMALIZED = $LIBXML2_LIB -replace '\\', '/'

    #     "LIBXML2_DIR=$LIBXML2_DIR_NORMALIZED" | Out-File -FilePath $env:GITHUB_ENV -Append
    #     "LIBXML2_LIB=$LIBXML2_LIB_NORMALIZED" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Install pnpm
      run: |
        npm install -g npm@latest
        npm install -g pnpm
      shell: bash
