name: Setup Environment
description: A reusable composite action to setup the environment.
inputs:
  os:
    description: The operating system to setup.
    required: true
runs:
  using: composite
  steps:
    - name: Install Linux packages
      if: contains(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libxml2-dev

    - name: Install macOS packages
      if: contains(inputs.os, 'macos')
      shell: bash
      run: brew install libxml2

    - id: setup-msys2
      uses: msys2/setup-msys2@v2
      if: contains(inputs.os, 'windows')
      with:
        update: true

    - name: Set MSYS2 location environment variable
      if: contains(inputs.os, 'windows')
      shell: bash
      run: |
        echo "MSYS2_LOCATION=${{ steps.setup-msys2.outputs.msys2-location }}" >> $GITHUB_ENV

    - name: Install Windows dependencies
      if: contains(inputs.os, 'windows')
      shell: msys2 {0}
      run: |
        pacman --noconfirm -S mingw-w64-x86_64-libxml2=2.15.1-2
