name: Setup Environment
description: A reusable composite action to setup the environment.
inputs:
  os:
    description: The operating system to setup.
    required: true
runs:
  using: composite
  steps:
    - name: Install Linux packages
      if: contains(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libxml2-dev

    - name: Install macOS packages
      if: contains(inputs.os, 'macos')
      shell: bash
      run: brew install libxml2 pkg-config

    - name: Install Windows packages
      if: contains(inputs.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64
        location: "C:\\msys64"
        install: libxml2 libxml2-devel
