name: Setup Environment
description: A reusable composite action to setup the environment.
inputs:
  os:
    description: The operating system to setup.
    required: true
  node-version:
    description: The Node.js version to setup.
    required: true
  architecture:
    description: The architecture to setup the node.js.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        architecture: ${{ inputs.architecture }}
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Install Linux packages
      if: contains(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libxml2-dev
        if [ ! -f /usr/lib/x86_64-linux-gnu/libxml2.a ] && [ ! -f /usr/lib/libxml2.a ] && [ ! -f /usr/lib64/libxml2.a ]; then
          echo "Warning: Static libxml2 library not found. Static linking may fall back to dynamic linking."
        fi

    - name: Install macOS packages
      if: contains(inputs.os, 'macos')
      shell: bash
      run: brew install libxml2 pkg-config

    - name: Install Windows packages
      if: contains(inputs.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64
        location: "C:\\msys64"
        install: libxml2-devel

    - name: Check for static libxml2 library on Windows
      if: contains(inputs.os, 'windows')
      shell: bash
      run: |
        if [ -f "C:/msys64/msys64/usr/lib/libxml2.a" ]; then
          echo "Static libxml2 library found"
        else
          echo "Warning: Static libxml2 library not found. The addon will require libxml2-2.dll at runtime."
          echo "Consider bundling the DLL or building libxml2 statically."
        fi

    - name: Install pnpm
      shell: bash
      run: |
        npm install -g npm@latest
        npm install -g pnpm
