name: Setup Environment
description: A reusable composite action to setup the environment.
inputs:
  os:
    description: The operating system to setup.
    required: true
  node-version:
    description: The Node.js version to setup.
    required: true
  architecture:
    description: The architecture to setup the node.js.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        architecture: ${{ inputs.architecture }}
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Install Linux packages
      if: contains(inputs.os, 'ubuntu')
      run: sudo apt update && sudo apt install -y libxml2-dev
      shell: bash

    - name: Install macOS packages
      if: contains(inputs.os, 'macos')
      run: brew install libxml2 pkg-config
      shell: bash

    - name: Install Windows packages
      if: contains(inputs.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64
        location: "C:"
        install: libxml2-devel

    - name: Install pnpm
      run: |
        npm install -g npm@latest
        npm install -g pnpm
      shell: bash
