import { StateCodes } from './state-code';

export default {
  [StateCodes.AC]: 'America/Rio_Branco',
  [StateCodes.AL]: 'America/Maceio',
  [StateCodes.AM]: 'America/Manaus',
  [StateCodes.AP]: 'America/Belem',
  [StateCodes.BA]: 'America/Bahia',
  [StateCodes.CE]: 'America/Fortaleza',
  [StateCodes.DF]: 'America/Sao_Paulo',
  [StateCodes.ES]: 'America/Sao_Paulo',
  [StateCodes.GO]: 'America/Sao_Paulo',
  [StateCodes.MA]: 'America/Fortaleza',
  [StateCodes.MG]: 'America/Sao_Paulo',
  [StateCodes.MS]: 'America/Campo_Grande',
  [StateCodes.MT]: 'America/Cuiaba',
  [StateCodes.PA]: 'America/Belem',
  [StateCodes.PB]: 'America/Fortaleza',
  [StateCodes.PE]: 'America/Recife',
  [StateCodes.PI]: 'America/Fortaleza',
  [StateCodes.PR]: 'America/Sao_Paulo',
  [StateCodes.RJ]: 'America/Sao_Paulo',
  [StateCodes.RN]: 'America/Fortaleza',
  [StateCodes.RO]: 'America/Porto_Velho',
  [StateCodes.RR]: 'America/Boa_Vista',
  [StateCodes.RS]: 'America/Sao_Paulo',
  [StateCodes.SC]: 'America/Sao_Paulo',
  [StateCodes.SE]: 'America/Maceio',
  [StateCodes.SP]: 'America/Sao_Paulo',
  [StateCodes.TO]: 'America/Araguaina',
} as const;
