name: Setup Node.js
description: A reusable composite action to setup the Node.js.
inputs:
  os:
    description: The operating system to setup the Node.js.
    required: true
  node-version:
    description: The Node.js version to setup the Node.js.
    required: true
  architecture:
    description: The architecture to setup the Node.js.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        architecture: ${{ inputs.architecture }}
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        always-auth: true

    - name: Install pnpm
      shell: bash
      run: |
        npm install -g npm@latest
        npm install -g pnpm

    # - id: setup-pnpm-store-path
    #   name: Setup pnpm store path
    #   shell: bash
    #   run: |
    #     echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    # - uses: actions/cache@v4
    #   env:
    #     STORE_PATH: ${{ steps.setup-pnpm-store-path.outputs.store_path }}
    #   with:
    #     path: ${{ env.STORE_PATH }}
    #     key: os:${{ inputs.os }}-${{ inputs.architecture }}|node:${{ inputs.node-version }}|pnpm:${{ hashFiles('pnpm-lock.yaml') }}
