import path from 'node:path';
import dotenv from 'dotenv';
import express from 'express';

import { DanfceDefaultPdfDocument } from './nfce/layouts/danfce-default';

dotenv.config({ path: path.resolve('../../', '.env') });
const app = express();

const SAMPLE_NFCE_XML = `<nfeProc xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
    <infNFe Id="NFe42251103916076000583650670000011301672406275" versao="4.00">
        <ide>
            <cUF>42</cUF>
            <cNF>67240627</cNF>
            <natOp>Venda de Produtor Rural</natOp>
            <mod>65</mod>
            <serie>67</serie>
            <nNF>1130</nNF>
            <dhEmi>2025-11-21T10:42:39-03:00</dhEmi>
            <tpNF>1</tpNF>
            <idDest>1</idDest>
            <cMunFG>4204301</cMunFG>
            <tpImp>4</tpImp>
            <tpEmis>1</tpEmis>
            <cDV>5</cDV>
            <tpAmb>2</tpAmb>
            <finNFe>1</finNFe>
            <indFinal>1</indFinal>
            <indPres>1</indPres>
            <procEmi>0</procEmi>
            <verProc>3.22.8</verProc>
        </ide>
        <emit>
            <CNPJ>03916076000583</CNPJ>
            <xNome>devszweb2@zucchetti.com</xNome>
            <xFant>devszweb2@zucchetti.com</xFant>
            <enderEmit>
                <xLgr>Rua Silvino Ciarini</xLgr>
                <nro>S/N</nro>
                <xCpl>teste</xCpl>
                <xBairro>Industriarios</xBairro>
                <cMun>4204301</cMun>
                <xMun>Concordia</xMun>
                <UF>SC</UF>
                <CEP>89705110</CEP>
                <cPais>1058</cPais>
                <xPais>BRASIL</xPais>
                <fone>99999999999</fone>
            </enderEmit>
            <IE>261471520</IE>
            <CRT>3</CRT>
        </emit>
        <dest>
            <CNPJ>03916076000583</CNPJ>
            <xNome>TESTE saiudh uiashd uiahdhasu</xNome>
            <enderDest>
              <xLgr>Rua Silvino Ciarini</xLgr>
              <nro>S/N</nro>
              <xCpl>teste</xCpl>
              <xBairro>Industriarios</xBairro>
              <cMun>4204301</cMun>
              <xMun>Concordia</xMun>
              <UF>SC</UF>
              <CEP>89705110</CEP>
              <cPais>1058</cPais>
              <xPais>BRASIL</xPais>
              <fone>99999999999</fone>
            </enderDest>
        </dest>
        <autXML>
            <CNPJ>03916076000583</CNPJ>
        </autXML>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350ml</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350ml</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350ml</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>319238921</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350ml</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>319238921312312312312</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350ml</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>asdijas98djas98</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350ml</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350mllllll</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350mlllll</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350mlllll</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>cProd com 60 caracteres igual ao schema para testar o layout</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>xProd com 120 caracteres igual ao schema para testar o layout e ver se o layout quebra a linha corretamente quando a des</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350mllll</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350mlll</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <det nItem="1">
            <prod>
                <cProd>3</cProd>
                <cEAN>7892509127080</cEAN>
                <xProd>Coca cola Lata 350mll</xProd>
                <NCM>00000000</NCM>
                <CFOP>5102</CFOP>
                <uCom>UN</uCom>
                <qCom>1.0000</qCom>
                <vUnCom>10.0000000000</vUnCom>
                <vProd>10.00</vProd>
                <cEANTrib>7892509127080</cEANTrib>
                <uTrib>UN</uTrib>
                <qTrib>1.0000</qTrib>
                <vUnTrib>10.0000000000</vUnTrib>
                <indTot>1</indTot>
            </prod>
            <imposto>
                <vTotTrib>1.49</vTotTrib>
                <ICMS>
                    <ICMS00>
                        <orig>0</orig>
                        <CST>00</CST>
                        <modBC>3</modBC>
                        <vBC>0.00</vBC>
                        <pICMS>0.0000</pICMS>
                        <vICMS>0.00</vICMS>
                    </ICMS00>
                </ICMS>
                <PIS>
                    <PISOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pPIS>0.0000</pPIS>
                        <vPIS>0.00</vPIS>
                    </PISOutr>
                </PIS>
                <COFINS>
                    <COFINSOutr>
                        <CST>99</CST>
                        <vBC>0.00</vBC>
                        <pCOFINS>0.0000</pCOFINS>
                        <vCOFINS>0.00</vCOFINS>
                    </COFINSOutr>
                </COFINS>
            </imposto>
        </det>
        <total>
            <ICMSTot>
                <vBC>0.00</vBC>
                <vICMS>0.00</vICMS>
                <vICMSDeson>0.00</vICMSDeson>
                <vFCP>0.00</vFCP>
                <vBCST>0.00</vBCST>
                <vST>0.00</vST>
                <vFCPST>0.00</vFCPST>
                <vFCPSTRet>0.00</vFCPSTRet>
                <vProd>10.00</vProd>
                <vFrete>0.00</vFrete>
                <vSeg>0.00</vSeg>
                <vDesc>0.00</vDesc>
                <vII>0.00</vII>
                <vIPI>0.00</vIPI>
                <vIPIDevol>0.00</vIPIDevol>
                <vPIS>0.00</vPIS>
                <vCOFINS>0.00</vCOFINS>
                <vOutro>0.00</vOutro>
                <vNF>10.00</vNF>
                <vTotTrib>1.49</vTotTrib>
            </ICMSTot>
        </total>
        <transp>
            <modFrete>9</modFrete>
        </transp>
        <pag>
            <detPag>
                <indPag>0</indPag>
                <tPag>01</tPag>
                <vPag>10.00</vPag>
            </detPag>
            <detPag>
                <indPag>0</indPag>
                <tPag>02</tPag>
                <vPag>10.00</vPag>
            </detPag>
            <detPag>
                <indPag>0</indPag>
                <tPag>03</tPag>
                <vPag>10.00</vPag>
            </detPag>
            <detPag>
                <indPag>0</indPag>
                <tPag>04</tPag>
                <vPag>10.00</vPag>
            </detPag>
            <detPag>
                <indPag>0</indPag>
                <tPag>05</tPag>
                <vPag>10.00</vPag>
            </detPag>
        </pag>
        <infAdic>
          <infCpl>;Trib aprox Fed: R$ 0,08, Est: R$ 0,07, Mun: R$ 0,00 ;/ Fonte: IBPT/empresometro.com.br 0D61CD</infCpl>
        </infAdic>
        <infRespTec>
            <CNPJ>03916076000400</CNPJ>
            <xContato>Bernardo Rachadel Junior</xContato>
            <email>bernardo.rachadel@zucchetti.com</email>
            <fone>4934420122</fone>
        </infRespTec>
    </infNFe>
    <infNFeSupl>
        <qrCode>
            https://hom.sat.sef.sc.gov.br/nfce/consulta?p=42251103916076000583650670000011301672406275|3|2</qrCode>
        <urlChave>https://hom.sat.sef.sc.gov.br/nfce/consulta</urlChave>
    </infNFeSupl>
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
            <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
            <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
            <Reference URI="#NFe42251103916076000583650670000011301672406275">
                <Transforms>
                    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
                </Transforms>
                <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                <DigestValue>p8O1oxNzRh6bE+IGelENFHrzc9g=</DigestValue>
            </Reference>
        </SignedInfo>
        <SignatureValue>
            WOIxU6UCW5T6DW0BXMPFXsNro1qcZzsSKt7EVuMJ9sN7/Poph1h4iuANgTgWwpXLFVX+SCRcaTKaFQ93t650fklPBbKSwkbG58SS7briNwZUhoSSFfXtfunpgyorQNm8vrHMTyLwjEq8hQLpXtOX782ONJ9Fii6IGx8owhZdKwR4ge4fAKrVcrdtchzLXtNEdr+PYZtCxH1w7kECVEwLsRMNqJcHLCd71OmwX9tIEZBYodLO+Vu4b7HNTfH2RmLf/cb6sD+azuB9ll/amUeUvE2KrrSvn7loH/eW66/d36ZldQfUe13jJhTfJkWFCUz6/tyh6srW1JCOwcyNH1y5aw==</SignatureValue>
        <KeyInfo>
            <X509Data>
                <X509Certificate>
                    MIIHSjCCBTKgAwIBAgIIYiQlEAJFSW4wDQYJKoZIhvcNAQELBQAwWTELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxFTATBgNVBAsTDEFDIFNPTFVUSSB2NTEeMBwGA1UEAxMVQUMgU09MVVRJIE11bHRpcGxhIHY1MB4XDTI1MTAwMjE0MDkwMFoXDTI2MTAwMjE0MDkwMFowgfIxCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMQswCQYDVQQIEwJTQzESMBAGA1UEBxMJQ29uY29yZGlhMR4wHAYDVQQLExVBQyBTT0xVVEkgTXVsdGlwbGEgdjUxFzAVBgNVBAsTDjMzNDE2MDc5MDAwMTk1MRwwGgYDVQQLExNDZXJ0aWZpY2FkbyBEaWdpdGFsMRowGAYDVQQLExFDZXJ0aWZpY2FkbyBQSiBBMTE6MDgGA1UEAxMxWlVDQ0hFVFRJIFNPRlRXQVJFIEUgU0lTVEVNQVMgTFREQTowMzkxNjA3NjAwMDU4MzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOVeuH4z9DxSQOjRDVdq8Zjt/l8nNmNFDXXd8p7MKh3QlsAAz4OquhNDhgU1O8t/UL3pM3y74e0UJCnbb7HxVvaupHsG9Y/NXvz40GFOnGsr2LJUT5n//M3EggCVYsbO5A4lTxSzK67SpkJ/XIcob7+0W1L3qsLzxcn1uiM5xPfzw2SywLIHacXqqvGFnCMihas+o9NYKZHDBiiM2xOJ1CGBP5lDYZOMwFxASODkAOfShiTBfh58vGgg9LDbGjSeQwBE1bov6xrqy5WhDB70HpXaFA1TY5ysv1gTXgkxZaj4/uW+A6gam1NUyJHec9kWbzkaCmKg7152g0RXbAS0DEkCAwEAAaOCAnowggJ2MAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUxVLtJYAJ35yCyJ9Hxt20XzHdubEwVAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjhodHRwOi8vY2NkLmFjc29sdXRpLmNvbS5ici9sY3IvYWMtc29sdXRpLW11bHRpcGxhLXY1LnA3YjCBtQYDVR0RBIGtMIGqgR1hbGVzc2lvLm1haW5hcmRpQHp1Y2NoZXR0aS5pdKAbBgVgTAEDAqASExBBTEVTU0lPIE1BSU5BUkRJoBkGBWBMAQMDoBATDjAzOTE2MDc2MDAwNTgzoDgGBWBMAQMEoC8TLTI3MDgxOTc1MDE4MjA3Njc0MTgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwXQYDVR0gBFYwVDBSBgZgTAECASYwSDBGBggrBgEFBQcCARY6aHR0cDovL2NjZC5hY3NvbHV0aS5jb20uYnIvZG9jcy9kcGMtYWMtc29sdXRpLW11bHRpcGxhLnBkZjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgYwGA1UdHwSBhDCBgTA+oDygOoY4aHR0cDovL2NjZC5hY3NvbHV0aS5jb20uYnIvbGNyL2FjLXNvbHV0aS1tdWx0aXBsYS12NS5jcmwwP6A9oDuGOWh0dHA6Ly9jY2QyLmFjc29sdXRpLmNvbS5ici9sY3IvYWMtc29sdXRpLW11bHRpcGxhLXY1LmNybDAdBgNVHQ4EFgQUeMGWZAOAA4H+pwd1EHuZUUCjliUwDgYDVR0PAQH/BAQDAgXgMA0GCSqGSIb3DQEBCwUAA4ICAQA8t9EGwDsnjfX7D39fH1cWU5d45qetTP0T8Cfa0xY9h1jyNyGIGaKEM1GimcAEXXvEJUdg36B0eyo9XXWL0Ns/BcJRBgwIi172HYS+5Md2o2TnQ9X3ncZXvitDDzZi6ZCt1Dd0pNNNfZrgPY2aXc0h9+LAPAHLJ3S507BWwwIbRijYuT2pWfFiPg1CPwhUFYMCGG/LV7RwAlOPBoZBtQWJWkyVBls6NF5n0ZZ3aIZyRIM8aKr8d818aUp0YBi0E8Cffx/JNS63Hc6p2jWxTz6UTlmFL4WEpKV1RcHc3QYnUtXjhqNsN613B/ndpeHaFTHbgCWoHxfNJYmO6/WcJLa/YiqKBQcRSkfGlTZsqEz7yG9VQnFLq+1sIswARtmcfnp4znAZcswEVPHUiM2PXvSCQKktUyxIJA6MdtBcxPcFNOfeez0ROVmR9p5kll+1eyUfqhL4JWPAkIx/QC3DxbhEeVga8RFQmSbRTBXYytj8QEQC+qYgYrVEboOXg63lSLMYTuTQ7nnQCrtue6tPpJXuWRvrYuMT0MlarQZDej5mvkKcHi4tGmkpYoqweZkuueVksGhsrc2c41iUEDGbHk4tPpHq2Huntl7Hut1S5BPnfT2qOXOdjbCy0FsKlYtQOFT6g6OLHqrfSKVqSlAQJ2lNkf7pBb8MRiGsRk20EAlmwQ==</X509Certificate>
            </X509Data>
        </KeyInfo>
    </Signature>
</NFe>
<protNFe versao="4.00">
    <infProt>
        <tpAmb>2</tpAmb>
        <verAplic>SVRSnfce2511121004</verAplic>
        <chNFe>42251103916076000583650670000011301672406275</chNFe>
        <dhRecbto>2025-11-21T10:42:40-03:00</dhRecbto>
        <nProt>342250000626207</nProt>
        <digVal>p8O1oxNzRh6bE+IGelENFHrzc9g=</digVal>
        <cStat>100</cStat>
        <xMotivo>Autorizado o uso da NF-e</xMotivo>
    </infProt>
</protNFe>
</nfeProc>`;

app.get('/danfce', async (_, res) => {
  res.set({
    'Content-Type': 'application/pdf',
    'Content-Disposition': 'inline; filename="example.pdf"',
    'Cache-Control': 'no-cache, no-store, must-revalidate',
  });

  const doc = new DanfceDefaultPdfDocument(res);
  await doc.build(SAMPLE_NFCE_XML);
  doc.end();
});

const PORT = process.env.PORT ? Number.parseInt(process.env.PORT, 10) : 3000;
app.listen(PORT, () => {
  console.log(`🚀 Dev server running at http://localhost:${PORT}`);
  console.log(`📄 Open your browser and refresh to generate a new PDF`);
});
